package dk.eatmore.foodapp.utils

class Constants {

    companion object {
        val FACEBOOK = "facebook"
        val GOOGLE = "google"
        val DIRECT = "direct"
        val R_TOKEN = "w5oRqFiAXTBB3hwpixAORbg_BwUj0EMQ07042017114812"
        val R_KEY = "fcARlrbZFXYee1W6eYEIA0VRlw7MgV4o07042017114812"
        val PAYMENTMETHOD="paymentmethod"
        val PROGRESSDIALOG="progressdialog"
        val AUTH_KEY="auth_key"
        val AUTH_VALUE="1025180533"
        val EATMORE_APP="eatmore_app"
        val USERNAME="username"
        val POSTAL_CODE="postal_code"
        val PASSWORD_HASH="password_hash"
        val FIRST_NAME="first_name"
        val EMAIL="email"
        val SUBSCRIBE="subscribe"
        val PAYMENTSTATUS="paymentstatus"
        val CUSTOMER_ID = "customer_id"
        val IS_LOGIN = "is_login"
        val OP_ID = "op_id"
        val P_ID = "p_id"
        val P_PRICE = "p_price"
        val P_QUANTITY = "p_quantity"
        val INGREDIENTS = "ingredients"
        val ATTRUBUTES = "attrubutes"
        val EXTRATOPPINGS = "extratoppings"
        val FB_ID="fb_id"
        val IS_FACEBOOK="is_facebook"
        val FB_EMAIL="fb_email"
        val DEVICE_TYPE="device_type"
        val DEVICE_TYPE_VALUE="Android"
        val R_KEY_N="r_key"
        val R_TOKEN_N="r_token"
        val RESTAURANT="restaurant"
        val IP="ip"
        val STATUS="status"
        val TITLE="title"
        val PRODUCTLIST="ProductList"
        val MENULIST="menulist"
        val OPEFTER="Opefter"

    }
}
