package dk.eatmore.foodapp.utils

class Constants {

    companion object {

    const  val FACEBOOK = "facebook"
    const  val GOOGLE = "google"
    const  val DIRECT = "direct"
    const  val R_TOKEN = "w5oRqFiAXTBB3hwpixAORbg_BwUj0EMQ07042017114812"
    const  val R_KEY = "fcARlrbZFXYee1W6eYEIA0VRlw7MgV4o07042017114812"
    const  val PAYMENTMETHOD_ONLINE="paymentmethod_online"
    const  val PROGRESSDIALOG="progressdialog"
    const  val AUTH_KEY="auth_key"
    const  val AUTH_VALUE="1025180533"
    const  val EATMORE_APP="eatmore_app"
    const  val USERNAME="username"
    const  val POSTAL_CODE="postal_code"
    const  val PASSWORD_HASH="password_hash"
    const  val FIRST_NAME="first_name"
    const  val EMAIL="email"
    const  val SUBSCRIBE="subscribe"
    const  val PAYMENTSTATUS="paymentstatus"
    const  val CUSTOMER_ID = "customer_id"
    const  val RESTAURANT_FOOD_ANDROID = "restaurant_food_android"
    const  val APP = "app"
    const  val IS_LOGIN = "is_login"
    const  val ID = "id"
    const  val OP_ID = "op_id"
    const  val P_ID = "p_id"
    const  val USER_DETAILS = "user_details"
    const  val P_PRICE = "p_price"
    const  val P_QUANTITY = "p_quantity"
    const  val INGREDIENTS = "ingredients"
    const  val ATTRUBUTES = "attrubutes"
    const  val EXTRATOPPINGS = "extratoppings"
    const  val FB_ID="fb_id"
    const  val IS_FACEBOOK="is_facebook"
    const  val FB_EMAIL="fb_email"
    const  val DEVICE_TYPE="device_type"
    const  val DEVICE_TYPE_VALUE="Android"
    const  val R_KEY_N="r_key"
    const  val R_TOKEN_N="r_token"
    const  val RESTAURANT="restaurant"
    const  val MENULISTITEM="menulistitem"
    const  val RESTAURANT_INFOMODEL="RestaurantInfoModel"
    const  val APP_ICON="app_icon"
    const  val IP="ip"
    const  val QUALITY_OF_FOOD="quality_of_food"
    const  val DELIVERY_TIME="delivery_time"
    const  val CUSTOMER_SERVICE="customer_service"
    const  val REVIEW="review"
    const  val STATUS="status"
    const  val ORDER_NO="order_no"
    const  val ENABLE_RATING="enable_rating"
    const  val ORDERRESULT="Orderresult"
    const  val ORDER_DATE="order_date"
    const  val TITLE="title"
    const  val ACCEPTED="accepted"
    const  val PRODUCTLIST="ProductList"
    const  val MENULIST="menulist"
    const  val OPEFTER="Opefter"
    const  val REORDER="Reorder"
    const  val CARTCOUNT_BROADCAST="cartcount_broadcast"
    const  val CARTCNT="cartcnt"
    const  val SHOW_MSG="show_msg"
    const  val CARTAMT="cartamt"
    const  val USER_INFO="user_info"
    const  val POSTAL_CITY="postal_city"
    const  val ORDER_TOTAL="order_total"
    const  val SHIPPING="shipping"
    const  val STREET="street"
    const  val HOUSE_NO="house_no"
    const  val FLOOR_DOOR="floor_door"
    const  val CITY="city"
    const  val TIME_LIST="time_list"
    const  val RESULT="result"
    const  val ACTUAL="actual"
    const  val DISPLAY="display"
    const  val ADDRESS="address"
    const  val ADDRESS_TITLE="address_title"
    const  val DISTANCE="distance"
    const  val TELEPHONE_NO="telephone_no"
    const  val MIN_ORDER_SHIPPING="min_order_shipping"
    const  val MINIMUM_ORDER_PRICE="minimum_order_price"
    const  val COMMENTS="comments"
    const  val EXPECTED_TIME="expected_time"
    const  val FIRST_TIME="first_time"
    const  val DISCOUNT_ID="discount_id"
    const  val DISCOUNT_TYPE="discount_type"
    const  val DISCOUNT_AMOUNT="discount_amount"
    const  val SHIPPING_CHARGE="shipping_charge"
    const  val SHIPPING_COSTS="shipping_costs"
    const  val UPTO_MIN_SHIPPING="upto_min_shipping"
    const  val ACCEPT_TC="accept_tc"
    const  val PAYMETHOD="paymethod"
    const  val CARTPRODUCTS="cartproducts"
    const  val ADDITIONAL_CHARGE="additional_charge"
    const  val ADDITIONAL_CHARGES_ONLINE="additional_charges_online"
    const  val ADDITIONAL_CHARGES_CASH="additional_charges_cash"
    const  val USER_DISTANCE="user_distance"
    const  val SHIPPING_REMARK="shipping_remark"
    const  val GIFTCARD="Giftcard"
    const  val COUPON="Coupon"
    const  val OTHER="Other"
    const  val MSG="msg"
    const  val WHOLE_SYSTEM="whole_system"
    const  val MESSAGE_TITLE="message_title"
    const  val MESSAGE_DETAILS="message_details"
    const  val TXNFEE="txnfee"
    const  val PAYMENTTYPE="paymenttype"
    const  val TXNID="txnid"
    const  val CARDNO="cardno"
    const  val EPAY_MERCHANT="epay_merchant"
    const  val EPAY_MERCHANT_TEST="8024206"
    const  val BOTTOM_TO_TOP_ANIM =200




    }
}
