package dk.eatmore.foodapp.utils

class Constants {

    companion object {
        val FACEBOOK = "facebook"
        val GOOGLE = "google"
        val DIRECT = "direct"
        val R_TOKEN = "w5oRqFiAXTBB3hwpixAORbg_BwUj0EMQ07042017114812"
        val R_KEY = "fcARlrbZFXYee1W6eYEIA0VRlw7MgV4o07042017114812"
        val PAYMENTMETHOD_ONLINE="paymentmethod_online"
        val PROGRESSDIALOG="progressdialog"
        val AUTH_KEY="auth_key"
        val AUTH_VALUE="1025180533"
        val EATMORE_APP="eatmore_app"
        val USERNAME="username"
        val POSTAL_CODE="postal_code"
        val PASSWORD_HASH="password_hash"
        val FIRST_NAME="first_name"
        val EMAIL="email"
        val SUBSCRIBE="subscribe"
        val PAYMENTSTATUS="paymentstatus"
        val CUSTOMER_ID = "customer_id"
        val IS_LOGIN = "is_login"
        val ID = "id"
        val OP_ID = "op_id"
        val P_ID = "p_id"
        val USER_DETAILS = "user_details"
        val P_PRICE = "p_price"
        val P_QUANTITY = "p_quantity"
        val INGREDIENTS = "ingredients"
        val ATTRUBUTES = "attrubutes"
        val EXTRATOPPINGS = "extratoppings"
        val FB_ID="fb_id"
        val IS_FACEBOOK="is_facebook"
        val FB_EMAIL="fb_email"
        val DEVICE_TYPE="device_type"
        val DEVICE_TYPE_VALUE="Android"
        val R_KEY_N="r_key"
        val R_TOKEN_N="r_token"
        val RESTAURANT="restaurant"
        val IP="ip"
        val STATUS="status"
        val ORDER_NO="order_no"
        val TITLE="title"
        val PRODUCTLIST="ProductList"
        val MENULIST="menulist"
        val OPEFTER="Opefter"
        val CARTCOUNT_BROADCAST="cartcount_broadcast"
        val CARTCNT="cartcnt"
        val CARTAMT="cartamt"
        val USER_INFO="user_info"
        val POSTAL_CITY="postal_city"
        val ORDER_TOTAL="order_total"
        val SHIPPING="shipping"
        val STREET="street"
        val HOUSE_NO="house_no"
        val FLOOR_DOOR="floor_door"
        val CITY="city"
        val TIME_LIST="time_list"
        val RESULT="result"
        val ACTUAL="actual"
        val DISPLAY="display"
        val ADDRESS="address"
        val ADDRESS_TITLE="address_title"
        val DISTANCE="distance"
        val TELEPHONE_NO="telephone_no"
        val MIN_ORDER_SHIPPING="min_order_shipping"
        val MINIMUM_ORDER_PRICE="minimum_order_price"
        val COMMENTS="comments"
        val EXPECTED_TIME="expected_time"
        val FIRST_TIME="first_time"
        val DISCOUNT_ID="discount_id"
        val DISCOUNT_TYPE="discount_type"
        val DISCOUNT_AMOUNT="discount_amount"
        val SHIPPING_CHARGE="shipping_charge"
        val SHIPPING_COSTS="shipping_costs"
        val UPTO_MIN_SHIPPING="upto_min_shipping"
        val ACCEPT_TC="accept_tc"
        val PAYMETHOD="paymethod"
        val CARTPRODUCTS="cartproducts"
        val ADDITIONAL_CHARGE="additional_charge"
        val ADDITIONAL_CHARGES_ONLINE="additional_charges_online"
        val ADDITIONAL_CHARGES_CASH="additional_charges_cash"
        val USER_DISTANCE="user_distance"
        val SHIPPING_REMARK="shipping_remark"
        val GIFTCARD="Giftcard"
        val COUPON="Coupon"
        val OTHER="Other"
        val MSG="msg"
        val TXNFEE="txnfee"
        val PAYMENTTYPE="paymenttype"
        val TXNID="txnid"
        val CARDNO="cardno"
        val EPAY_MERCHANT="epay_merchant"
        val EPAY_MERCHANT_TEST="8024206"




    }
}
